# Generated by Django 5.2.17 on 2026-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="delivery_error",
            field=models.TextField(blank=True, verbose_name="Ошибка отправки"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка отправки"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус отправки письма",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отправки письма"
            ),
        ),
    ]
